version: '3.8'
services:
    unidragon-service-nginx:
        image: nginx
        container_name: "unidragon-service-nginx"
        ports:
            - "80:80"
        links:
            - unidragon-service-ruby
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
    unidragon-service-ruby:
        image: ruby:2.6.0
        container_name: "unidragon-service-ruby"
        command: bash -c "/unidragon-service/initial-setup.sh"
        volumes:
            - ./src:/unidragon-service
            - ./config/ruby/initial-setup-dev.sh:/unidragon-service/initial-setup.sh
